{% set version = "3.0.0" %}

package:
  name: audioread
  version: {{ version }}

source:
  fn: audioread-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/audioread/audioread-{{ version }}.tar.gz
  sha256: 121995bd207eb1fda3d566beb851d3534275925bc35a4fb6da0cb11de0f7251a

build:
  number: 1
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - ffmpeg  # [not win]

test:
  requires:
    - pytest
    - pytest-runner
  imports:
    - audioread

about:
  home: https://github.com/beetbox/audioread
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: multi-library, cross-platform audio decoding

extra:
  recipe-maintainers:
    - bmcfee
    - sampsyo
    - scopatz
    - mfansler
